apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-repro
  namespace: appset-repro
spec:
  destination:
    namespace: appset-repro
    server: https://kubernetes.default.svc
  sources:
    - ref: values
      repoURL: https://github.com/agiorgirh/appset-repro.git
      targetRevision: main
    - chart: appset-repro
      helm:
        ignoreMissingValueFiles: true
        parameters:
          - name: ClusterName
            value: aleocp
        releaseName: appset-repro
        skipCrds: true
        valueFiles:
          - $values/values.yaml
          - $values/values_overrides.yaml
      path: appset-repro
      repoURL: quay.io/rh_ee_algiorgi
      targetRevision: 0.2.0
  project: default
